### PR TITLE
Created a crawler for marathi website lokmat.com , issue #52

### LINKED ISSUE #52: Working on crawler for Marathi website lokmat
Started working on creating a crawler for Marathi website https://www.lokmat.com/

### PR DESCRIPTION
**Pull request by athJ**
Fixed #52 , crawler created

### CODE REVIEW

**Comment by adamshamsudeen** [comment]
can you also update the readme with the crawler information?

**Comment by athJ** [comment]
Sure , I'll do that

**Comment by athJ** [comment]
@adamshamsudeen After I make the changes , will I have to create a new PR ?

**Comment by athJ** [comment]
@adamshamsudeen , done !

**Comment by adamshamsudeen** [comment]
Thank you :)

**Pull request merged**
