### PR TITLE
Add Mathrubhumi Crawler

### PR DESCRIPTION
**Pull request by anoopmsivadas**
modified the same multithreaded script for [Mathrubhumi](https://www.mathrubhumi.com/)
but it seems to have some English text in some pages which I couldn't remove

### CODE REVIEW

**Comment by adamshamsudeen** [comment]
Hey, this looks good. When you ran the crawler what percentage of the article is in English? 
Anyways when we run the preprocessing script all the English words are [removed](https://github.com/vanangamudi/newspaper-crawler-scripts/blob/5184ab06d0c0a63de13efbed0c3b95175f0be8ae/malayalam/processing_scripts/word_freq.py#L42).  If you wish you can all add this to the crawler.

**Comment by adamshamsudeen** [comment]
This script is running for the last 2 days, I'll update the data size once it's done scrapping.

**Comment by anoopmsivadas** [comment]
ah sorry for the late reply, some of the pages has a line containing content highlights

**Comment by adamshamsudeen** [comment]
Can you share an example?

**Pull request merged**
